development:
  server: "http://demo1.codingmart.com:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "7a366dc04bf244c5199be1c7bd8944cdddfc562a0519a0692ec9dfb30d4b69e1"
  signature_expiration: 3600 # one hour
